include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true # dart fix --applyで実行

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore