name: yumemi_flutter_codecheck
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_flavor: ^3.1.4
  flutter_localizations:
    sdk: flutter  
  hooks_riverpod: ^3.0.0
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  auto_route: ^10.1.2
  retrofit: ^4.7.2
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.4
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_lint: ^3.0.0
  build_runner: ^2.7.1
  flutter_flavorizr: ^2.4.1
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  retrofit_generator: ^10.0.0

flutter:
  generate: true 
  uses-material-design: true
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "Codecheck Dev"
      android:
        applicationId: "com.firebaseapp.yumemi_flutter_codecheck_dev"
      ios:
        bundleId: "com.firebaseapp.yumemiFlutterCodecheckDev"
    prod:
      app:
        name: "Codecheck"
      android:
        applicationId: "com.firebaseapp.yumemi_flutter_codecheck"
      ios:
        bundleId: "com.firebaseapp.yumemiFlutterCodecheck"
